#!/bin/bash
# Format: http://dep.debian.net/deps/dep5/
# Files: *
# Copyright: Copyright 2011, Canonical Ltd., All Rights Reserved.
# License: GPL-3
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
########################################################################
# file config-changed 
# brief manage the config changes of floodlight controller, and occurs everytime a new configuration value is updated (juju set)
# author  kharade@eurecom.fr

set -e
source $CHARM_DIR/utils/common

status-set maintenance "Config-Changed hook"
stop_floodlight


