#!/bin/bash
# Format: http://dep.debian.net/deps/dep5/
# Files: *
# Copyright: Copyright 2011, Canonical Ltd., All Rights Reserved.
# License: GPL-3
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
########################################################################
# file install 
# brief install the floodlight sdn controller
# author  kharade@eurecom.fr

set -e

status-set maintenance "Installing dependencies"
sudo apt update -y
sudo apt install git -y
sudo apt-get install build-essential ant maven python-dev -y
sudo apt-get install build-essential openjdk-8-jdk ant maven python-dev eclipse -y

status-set maintenance "Setting Java Home"
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
PATH=$PATH:$HOME/bin:$JAVA_HOME/bin
export JAVA_HOME
export JRE_HOME
export PATH

status-set maintenance "Cloning floodlight v1.2"
git clone -b v1.2  git://github.com/floodlight/floodlight.git
cd floodlight
git submodule init
git submodule update

status-set maintenance "Building floodlight v1.2"
ant
sudo mkdir /var/lib/floodlight
sudo chmod 777 /var/lib/floodlight
cd ../

status-set maintenance "Calling start hook"
./hooks/start


