#!/bin/bash
set -e
status-set maintenance "Installing zip package."
sudo apt update -y
sudo apt install git -y
sudo apt-get install build-essential ant maven python-dev -y
sudo apt-get install build-essential openjdk-8-jdk ant maven python-dev eclipse -y
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
PATH=$PATH:$HOME/bin:$JAVA_HOME/bin
export JAVA_HOME
export JRE_HOME
export PATH
git clone -b v1.2  git://github.com/floodlight/floodlight.git
cd floodlight
git submodule init
git submodule update
ant
sudo mkdir /var/lib/floodlight
sudo chmod 777 /var/lib/floodlight

cd floodlight/ && java -jar ./target/floodlight.jar
# exec ./hooks/start
status-set maintenance "Active"

